baseURL = 'https://arihant2math.github.io'
languageCode = 'en-us'
title = "Ashwin's Website"
enableRobotsTXT = true
theme = 'custom'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 2

[[menus.main]]
name = 'Research'
pageRef = '/research'
weight = 3

[outputs]
home = ["HTML", "RSS", "JSON"]
