baseURL = 'https://arihant2math.github.io'
languageCode = 'en-us'
title = "Ashwin's Website"
enableRobotsTXT = true
theme = 'custom'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 2

[[menus.main]]
name = 'Music'
pageRef = '/music'
weight = 3

[[menus.main]]
name = 'Publications'
pageRef = '/publications'
weight = 4

[[menus.main]]
name = 'Search'
pageRef = '/search'
weight = 99

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
defaultTheme = "auto"

[[params.socialIcons]]
name = "github"
url = "https://github.com/arihant2math/"