name = 'Custom Theme'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme for my website'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/arihant2math/arihant2math.github.io'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
# tags = ['blog', 'company']
# features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Ashwin Naren'
  homepage = 'https://arihant2math.github.io'
